ekf_filter_node:  
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  false, false]
    imu0_queue_size: 10

    odom0: /odom
    odom0_config: [true,  true,  false,
                  false, false, true,
                  false, false, false,
                  false, false, false]
    odom0_queue_size: 10

    output_frame: odom
    publish_tf: true
    print_diagnostics: true
