controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.05  # 四足侧移能力
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 20.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2  # 增大位置容差
      yaw_goal_tolerance: 0.2  # 增大角度容差
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5  # 降低线速度
      lookahead_dist: 0.4
      min_lookahead_dist: 0.2
      max_lookahead_dist: 0.6
      rotate_to_heading_angular_vel: 0.8  # 降低旋转速度
      max_angular_accel: 1.5  # 减小角加速度
      use_rotate_to_heading: true
      allow_reversing: true  # 允许倒车
      max_robot_pose_search_dist: 5.0

planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5  # 增大目标点容差

# bt_navigator:
#   ros__parameters:
#     use_sim_time: True
#     bt_loop_duration: 10
#     default_server_timeout: 20
#     global_frame: map
#     robot_base_frame: base_link
#     transform_timeout: 0.5
#     default_nav_to_pose_bt_xml: "/home/cennum/cyberdog_sim/src/cyberdog_control/cyberdog_nav2/behavior_trees/navigate_to_pose.xml"
#     # default_nav_through_poses_bt_xml: "package://cyberdog_nav2/behavior_trees/navigate_through_poses.xml"
#     plugin_lib_names:
#     - nav2_compute_path_to_pose_action_bt_node
#     - nav2_follow_path_action_bt_node
#     - nav2_wait_action_bt_node
#     - nav2_clear_costmap_service_bt_node
#     - nav2_goal_reached_condition_bt_node


local_costmap:
  ros__parameters:
    update_frequency: 3.0
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 4
    height: 4
    resolution: 0.05
    robot_radius: 0.2
    plugins: ["static_layer", "inflation_layer"]
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 5.0
      inflation_radius: 0.0
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 0.5
    resolution: 0.05
    plugins: ["static_layer", "inflation_layer"]
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.0
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "map1.yaml"


waypoint_follower:
  ros__parameters:
    use_sim_time: True            # 仿真请改为 True
    stop_on_failure: false         # 遇到单点失败是否停止
    loop_rate: 20                  # 检查导航任务结果的频率
    waypoint_task_executor_plugin: "wait_at_waypoint"  # 指定要加载的插件 ID
    wait_at_waypoint:              # 与上面插件 ID 保持一致的名称
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"  # 插件完整类名
      enabled: True                # 是否启用
      waypoint_pause_duration: 200 # 停留时长（毫秒）
